---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bhadrika/public_html/link.domain
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt sitemap.xml llms.txt llms-full.txt llm.txt security.txt $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/src/img
    - /bin/cp src/output.css $DEPLOYPATH/src/output.css
    - /bin/cp src/main.js $DEPLOYPATH/src/main.js
    - /bin/cp src/img/* $DEPLOYPATH/src/img/
    - /bin/mkdir -p $DEPLOYPATH/.well-known
    - /bin/cp .well-known/security.txt $DEPLOYPATH/.well-known/security.txt
